name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  Dependances:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get install wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
        pip install cyclonedx-bom
        cyclonedx-py requirements -i requirements.txt -o sbom.json

    - name: Scan Trivy
      run: |
         trivy sbom --scanners vuln --exit-code 1 sbom.json

         
  Dockerfile:
      name: Scanner Dockerfile
      runs-on: ubuntu-latest
      needs: Dependances
  
      steps:
        - name: Checkout du code
          uses: actions/checkout@v4
  
        - name: Vérifier présence Dockerfile
          run: |
            if [ ! -f Dockerfile ]; then
              echo "Dockerfile manquant"
              exit 1
            fi
  
        - name: Lint du Dockerfile avec Hadolint
          uses: hadolint/hadolint-action@v3.2.0
          with:
            dockerfile: Dockerfile
            
        - name: Analyse Trivy de l'image Docker
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: config
            scan-ref: Dockerfile
            scanners: config
            format: table
            exit-code: 0
  security-trivy:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest
    permissions:
      contents: read # Nécessaire pour checkout
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Scan Trivy (FS & Dockerfile)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy-report.html'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Upload du rapport HTML
        uses: actions/upload-artifact@v4
        if: always() # Important : Upload même si Trivy trouve des failles
        with:
          name: rapport-securite-trivy
          path: trivy-report.html
          retention-days: 5
